src/protected/models/Report.php
<?php

Yii::import('application.models._base.BaseReport');

/**
 * [Report description]
 *
 * @author   Christian Micklisch <cmicklis@stetson.edu>, John Salis <jsalis@stetson.edu>
 * @since 	 v1.0.0
 */
class Report extends BaseReport
{
	const SCOPE_IDENTIFIER = '#';

	public static function model($className = __CLASS__)
	{
		return parent::model($className);
	}

	/**

		Query Builder

	 */

	/**
	 * [buildQuery description]
	 * 
	 * @param  [type] $model [description]
	 * @param  [type] $input [description]
	 */
	public function buildQuery($model, $input)
	{
		$fieldCriteria = new CDbCriteria;

		// Iterate through each attribute.
		foreach ($input as $attribute => $criteria)
		{
			$isScope = ($attribute[0] == Report::SCOPE_IDENTIFIER);
			$isRange = !isset($criteria['value']);
			$isCustom = !array_key_exists($attribute, $model->attributes);

			$attrCriteria = new CDbCriteria;

			if ($isRange)
			{
				foreach ($criteria['from'] as $index => $from)
				{
					$to = $criteria['to'][$index];

					if ($isScope)
					{
						$scope = substr($attribute, 1);
						$attrCriteria->mergeWith($model->$scope($from, $to, true), 'OR');
					}
					else if ($isCustom)
					{
						$model->filterField($attribute, array($from, $to), $fieldCriteria);
					}
					else
					{
						$attrCriteria->addBetweenCondition($attribute, $from, $to, 'OR');
					}
				}
			}
			else
			{
				foreach ($criteria['value'] as $index => $value)
				{
					if ($isScope)
					{
						$scope = substr($attribute, 1);
						$attrCriteria->mergeWith($model->$scope($value, true), 'OR');
					}
					else if ($isCustom)
					{
						$model->filterField($attribute, $value, $fieldCriteria);
					}
					else
					{
						$attrCriteria->compare($attribute, $value, false, 'OR');
					}
				}
			}

			$model->getDbCriteria()->mergeWith($attrCriteria);
		}

		$model->getDbCriteria()->mergeWith($fieldCriteria);
	}
}

src/protected/controllers/ReportController.php
<?php

/**
 * The ReportController class is there to act as a middle man between all of the views in which the
 * user selects what he wants (reservations from a specific time, with a specific item, ...) and
 * then either allows the user to display all of that information or download it in a csv format.
 *
 * @author   Christian Micklisch <cmicklis@stetson.edu>, John Salis <jsalis@stetson.edu>
 * @since 	 v1.0.0	
 */
class ReportController extends Controller
{
	protected $publicActions = array('fetchCriteria');

	/**
	 * [actionReservation description]
	 */
	public function actionReservation()
	{
		if (isset($_POST['Criteria']))
		{
			$model = Reservation::model()->currentBranch();

			Report::model()->buildQuery($model, $_POST['Criteria']);

			$this->render('results', array(
				'rows' => $model->findAll()
			));
		}
		else
		{
			$this->render('search-reservation');
		}
	}

	/**
	 * [actionItem description]
	 */
	public function actionItem()
	{
		if (isset($_POST['Criteria']))
		{
			$model = Item::model()->currentBranch();

			Report::model()->buildQuery($model, $_POST['Criteria']);

			$this->render('results', array(
				'rows' => $model->findAll()
			));
		}
		else
		{
			$this->render('search-item');
		}
	}

	/**
	 * AJAX-Only Request.
	 * 
	 * [fetchCriteria description]
	 */
	public function actionFetchCriteria()
	{
		if (Yii::app()->request->isAjaxRequest)
		{
			$label = ucwords(str_replace('_', ' ', $_GET['label']));
			
			$this->renderPartial('_criteria', array(
				'label' => $label,
				'attribute' => $_GET['attribute'],
				'inputType' => $_GET['inputType'],
				'comparable' => $_GET['comparable'],
			), false, true);

			Yii::app()->end();
		}
		else
		{
			throw new CHttpException('400', 'Invalid request.');
		}
	}
}

src/protected/views/report/_criteria.php
<?php
	/**
	 * Renders a search criteria input for a single attribute.
	 * 
	 * @param string  $attribute    The name of the attribute.
	 * @param string  $inputType    The path to the input widget.
	 * @param boolean $comparable   Whether the input is comparable.
	 */
	
	$label = (isset($label)) ? $label : ucwords(str_replace(array('-', '_', '.'), ' ', $attribute));

	$inputName = 'Criteria[' . $attribute . ']';
?>

<div class="panel panel-default">
	<div class="panel-body">
		<div class="row">
			<div class="col-xs-4">
				<div class="input-group">
					<span class="input-group-btn">
						<button type="button" class="close close-panel" style="margin-right: 15px">&times;</button>
					</span>
					<p class="criteria-label dynamic-label form-control-static"><?php echo $label; ?></p>
				</div>
			</div>
			<div class="col-xs-8">
				<div class="row">
					<?php
						if ($comparable)
						{
							echo '<div class="col-xs-5">';
							$this->widget($inputType, array('name' => $inputName . '[from][]'));
							echo '</div>';

							echo '<div class="col-xs-2">';
							echo '<p class="form-control-static text-center">to</p>';
							echo '</div>';

							echo '<div class="col-xs-5">';
							$this->widget($inputType, array('name' => $inputName . '[to][]'));
							echo '</div>';
						}
						else
						{
							echo '<div class="col-xs-6">';
							echo '<p class="form-control-static">equals</p>';
							echo '</div>';

							echo '<div class="col-xs-6">';
							$this->widget($inputType, array('name' => $inputName . '[value][]'));
							echo '</div>';
						}
					?>
				</div>
			</div>
		</div>
	</div>
</div>

src/protected/views/report/_search.php
<?php
	/**
	 * Renders a customizable search form using a set of criteria.
	 * 
	 * @param string $title          The title of the form.
	 * @param string $action         The action of the form.
	 * @param array  $criteriaList   The list of available search criteria.
	 */
	
	Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl . '/js/site/report.js', CClientScript::POS_END);

	$ajaxOptions = array('success' => 'js:addCriteria');
	$htmlOptions = array('class' => 'list-group-item dynamic-label');

	asort($criteriaList);

	$limits = array();

	foreach ($criteriaList as $criteria)
	{
		$label = ucwords(str_replace('_', ' ', $criteria['label']));
		$limits[ $label ] = $criteria['limit'];
		unset($criteria['limit']);
	}
?>

<script>
    var limits = <?php echo json_encode($limits); ?>;
</script>

<div class="col-xs-12 form-group">
	<span class="h3 dynamic-label"><?php echo $title; ?></span>
</div>
<div class="col-xs-12 col-sm-3">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title">Add Criteria</h3>
		</div>
		<div id="search_criteria" class="panel-body list-group">
			<?php
				foreach ($criteriaList as $criteria)
				{
					$url = array_merge(array('report/fetchCriteria'), $criteria);
					$label = ucwords(str_replace('_', ' ', $criteria['label']));

					echo CHtml::ajaxLink($label, $url, $ajaxOptions, $htmlOptions);
				}
			?>
		</div>
	</div>
</div>
<div class="col-xs-12 col-sm-9">
	<form id="search_form" action="<?php echo $action; ?>" method="post" class="form-horizontal">
		<?php
			echo CHtml::submitButton('Search', array('class' => 'btn btn-primary pull-right'));
		?>
	</form>
</div>

src/protected/views/report/results.php
<div class="col-xs-12">
    
    <!-- No Results Alert -->
    <div class="alert alert-warning <?php if (count($rows) > 0) { echo 'hide'; } ?>">
        No results found.
    </div>

    <!-- Results Table -->
    <div class="<?php if (count($rows) == 0) echo 'hide'; ?>">
        <div class="panel panel-default scroll-hor">
            <?php
                if (count($rows) > 0)
                {
                    $this->renderPartial('/manage/_table', array(
                        'model' => $rows[0],
                        'rows' => $rows,
                    ));
                }
            ?>
        </div>
        <form class="report-form" action="/" method="post">
            <input name="Report[download]" type="text" class="hide" value="1">
            <button class="btn btn-primary" type="submit">Download CSV</button>
        </form>
    </div>

</div>

src/protected/views/report/search-item.php
<?php
	$model = new Item;
	$inputTypes = $model->inputTypes();
	$comparableList = CHtml::listData(InputType::model()->findAll(), 'pathToWidget', 'comparable');

	$criteriaList = array(
		array(
			'label' => 'Item_Status',
			'attribute' => 'item_status_id',
			'inputType' => InputType::model()->getPathToWidget(InputType::ITEM_STATUS),
			'comparable' => false,
			'limit' => 3,
		),
		array(
			'label' => 'Item_Type',
			'attribute' => 'item_type_id',
			'inputType' => InputType::model()->getPathToWidget(InputType::ITEM_TYPE),
			'comparable' => false,
			'limit' => 3,
		),
		array(
			'label' => 'Reserved',
			'attribute' => Report::SCOPE_IDENTIFIER . 'reserved',
			'inputType' => InputType::model()->getPathToWidget(InputType::DATE_TIME),
			'comparable' => true,
			'limit' => 3,
		),
	);

	foreach (array_keys($model->getFields()) as $name)
	{
		$criteriaList[] = array(
			'label' => $name,
			'attribute' => $name,
			'inputType' => $inputTypes[ $name ],
			'comparable' => $comparableList[ $inputTypes[ $name ] ],
			'limit' => 1,
		);
	}

	$this->renderPartial('_search', array(
		'title' => 'Search Items',
		'action' => $this->createUrl('report/item'),
		'criteriaList' => $criteriaList,
	));
?>

src/protected/views/report/search-reservation.php
<?php
	$model = new Reservation;
	$inputTypes = $model->inputTypes();
	$comparableList = CHtml::listData(InputType::model()->findAll(), 'pathToWidget', 'comparable');

	$criteriaList = array(
		array(
			'label' => 'User',
			'attribute' => 'user_id',
			'inputType' => InputType::model()->getPathToWidget(InputType::USER),
			'comparable' => false,
			'limit' => 3,
		),
		array(
			'label' => 'Location',
			'attribute' => 'location_id',
			'inputType' => InputType::model()->getPathToWidget(InputType::LOCATION),
			'comparable' => false,
			'limit' => 3,
		),
		array(
			'label' => 'Reservation_Status',
			'attribute' => Report::SCOPE_IDENTIFIER . 'status',
			'inputType' => InputType::model()->getPathToWidget(InputType::RESERVATION_STATUS),
			'comparable' => false,
			'limit' => 3,
		),
		array(
			'label' => 'Date_Range',
			'attribute' => Report::SCOPE_IDENTIFIER . 'dateRange',
			'inputType' => InputType::model()->getPathToWidget(InputType::DATE_TIME),
			'comparable' => true,
			'limit' => 3,
		),
		array(
			'label' => 'Item_Type',
			'attribute' => Report::SCOPE_IDENTIFIER . 'itemType',
			'inputType' => InputType::model()->getPathToWidget(InputType::ITEM_TYPE),
			'comparable' => false,
			'limit' => 3,
		),
		array(
			'label' => 'Item_Status',
			'attribute' => Report::SCOPE_IDENTIFIER . 'itemStatus',
			'inputType' => InputType::model()->getPathToWidget(InputType::ITEM_STATUS),
			'comparable' => false,
			'limit' => 3,
		),
	);

	foreach (array_keys($model->getFields()) as $name)
	{
		$criteriaList[] = array(
			'label' => $name,
			'attribute' => $name,
			'inputType' => $inputTypes[ $name ],
			'comparable' => $comparableList[ $inputTypes[ $name ] ],
			'limit' => 1,
		);
	}

	$this->renderPartial('_search', array(
		'title' => 'Search Reservations',
		'action' => $this->createUrl('report/reservation'),
		'criteriaList' => $criteriaList,
	));
?>